### ISSUE TITLE
Names error most likely on my part

### ISSUE THREAD

**Issue by tuffboy807** [r00t-64/gmail-account-generator#1]
I keep getting a error I installed names using Pip and I receive this error each time like I said its probably something minor on my side I messed up but any help would be appreciated
Traceback (most recent call last):
  File "/home/kali/gmail-account-generator/gmkacc.py", line 107, in <module>
    instance.writefile(9)
  File "/home/kali/gmail-account-generator/gmkacc.py", line 78, in writefile
    f.write(acc[ii] + '\t' + pss[ii] + '\t' + names.get_full_name())
NameError: name 'names' is not defined

**Comment by GamerGirlandCo** [comment]
hey! i figured it out. replace `names.get_full_name()` with `src.names.get_full_name()` :)
